language: node_js
node_js:
  - 15

install:
  - npm install

script:
  - npm test

services:
  - docker
  - mongodb

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

