language: node_js
node_js:
  - 15

install:
  - npm install

before_script:
  - openssl aes-256-cbc -K $encrypted_555b4132f40f_key -iv $encrypted_555b4132f40f_iv -in ./config/google_cloud_api_key_2.json.enc -out ./config/google_cloud_api_key_2.json -d

script:
  - npm test

