let mongoose = require('mongoose');
let Schema = mongoose.Schema;
const bcrypt = require('bcrypt');

// This file defines the User objects that will be saved to the db

let UserSchema = new Schema({
    // id: {type: String}, this id will be autogenerated by mongodb
    email: {type: String, required: true},
    password: {type: String, required: true},
    images: Array,
    follows: Array,
    followers: Array,
    likes: Array
});


// Middleware before saving the User object to the db:
UserSchema.pre('save', async function (next) {

    const user = this;
    user.password = await bcrypt.hash(user.password, 10);
    next();

})

const User = mongoose.model('User', UserSchema);

module.exports = User;
